FROM	alpine

RUN		apk add mariadb mariadb-client && \
		apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache && \
		mkdir -p /run/mysqld

#Include all option files in a directory from another option file (/etc/my.cnf.d)
COPY	/srcs/mariadb.cnf			/etc/my.cnf.d/
COPY	/srcs/telegraf.conf			/etc/telegraf/
COPY	/srcs/wordpress.sql			/
COPY	/srcs/start.sh				/

EXPOSE	3306

ENTRYPOINT	sh start.sh
